### ISSUE TITLE
title & control buttons not scaling properly

### ISSUE THREAD

**Issue by kanenr** [leeprky/WindowsXI#1]
the title & control buttons are bigger than the top bar itself when the application is maximized.
tested on windows 10 with varying resolutions w/ powercord
showcase: [imgur album](https://imgur.com/a/ixynkN8)

**Comment by leeprky** [comment]
https://github.com/leeprky/leeprky.github.io/commit/adbc94acf7653592f54541b5405d927bbd0b4751

**Comment by leeprky** [comment]
Second Part is just powercord/discord issue
