### ISSUE TITLE
Light mode in settings not working correctly.

### ISSUE THREAD

**Issue by snappyapple632** [leeprky/WindowsXI#2]
When using light mode and entering Discord's setting menu, the background darkens regardless of which mode you are using. In light mode, the text uses a dark color, making them hard to see. I was able to reproduce this issue on two different devices using the steps below.

## To reproduce:
1) Open Discord's settings menu.
2) Switch to light mode if not already done.
3) Observe results.

## Screenshots 

The first is on a device running the latest Windows 11 dev build, the second is on the latest stable build of Windows 10. The issue is present on both devices.
![Screenshot 2021-07-22 145932](https://user-images.githubusercontent.com/40573129/126719535-2c43bc7b-c5a9-4b26-a6fb-a430f9484215.png)
![Screenshot 2021-07-22 160135](https://user-images.githubusercontent.com/40573129/126719538-ae454e92-b207-4b0c-9c19-8cb9592b8414.png)

**Comment by leeprky** [comment]
possibly fixed
