### ISSUE TITLE
Is there a Raw file without any import

### ISSUE THREAD

**Issue by Josh65-2201** [leeprky/WindowsXI#3]
I would like to customise this however it currently used a bunch of imports. Is there any file that has all the necessary (and non third party imports) code raw in one file.

**Comment by leeprky** [comment]
https://github.com/leeprky/leeprky.github.io/blob/gh-pages/themes/WindowsXI/compiled.css

OR

QuickCSS

**Comment by Josh65-2201** [comment]
Thanks

**Comment by Josh65-2201** [comment]
I get this error when trying to use it
![image](https://user-images.githubusercontent.com/26977075/127657884-1540c2ea-c852-406c-b868-1634372c4115.png)
