### ISSUE TITLE
Unread indicators not visible in light mode.

### ISSUE THREAD

**Issue by snappyapple632** [leeprky/WindowsXI#5]
Title is self-explanatory.

In screenshots: #show-room has unread messages and shows indicator in dark mode but not light mode.
![Dark](https://user-images.githubusercontent.com/40573129/128641582-3b824465-8d0b-4b13-a734-3b8b23eaaa5d.png)
![Light](https://user-images.githubusercontent.com/40573129/128641583-54972656-49ca-439d-966d-1f2abe5e34f2.png)

**Comment by leeprky** [comment]
It Does But Its Because Its Way To Light In Light Mode - Correcting it now
