### ISSUE TITLE
Plugin compatibility

### ISSUE THREAD

**Issue by buficek7** [leeprky/WindowsXI#8]
Hi. I really like this discord theme. It's exactly what I was looking for. It has one problem though. I really like using this 
Plugin: https://betterdiscord.app/plugin/ReadAllNotificationsButton
This plugin displays a button on the top left. In all the other layouts it works, but unfortunately not here. Do you think there is any way to fix this?

![obrazek](https://user-images.githubusercontent.com/65396141/135916114-7b1574b1-ee5e-438c-ab8d-587cead73e45.png)
![obrazek](https://user-images.githubusercontent.com/65396141/135916162-ade43343-4518-45af-9499-dfe9b7bfadd8.png)

**Comment by leeprky** [comment]
You Can Enable Disable Those In The Config
